### ISSUE TITLE
[Bug] Grand Shelter devotion cannot be collected

### ISSUE THREAD

**Issue by Tokadrop** [Ciarenni/COTL_MysticAssistant#2]
The latest update v2.0.0 has made it so i can no longer right click on grand shelter's to collect their devotion, prior to this update it worked alright. 
Below is the error i get when attempting to do so:
![errrr](https://github.com/user-attachments/assets/9a292ba5-fb19-417e-9f4b-cb71157d01eb)

**Comment by Ciarenni** [comment]
I was able to reproduce the issue with Grand Shelters and pushed a new version that should fix it. This was an issue I had previously fixed but re-introduced with a lapse of focus, so I apologize for the inconvenience. NexusMods and Thunderstore are both updated with the new version as well, so if you got the mod from one of those, you can simply update from there. Thanks for letting me know about this issue!
